// import { firebase } from 'firebase/app';
import { initializeApp  } from "Firebase/app"
import  { getFirestore, collection, addDoc } from 'firebase/firestore'

// import {collection, doc, setDoc} from "firebase/firestore"
var firebaseConfig = {
    apiKey: "AIzaSyC44jHOd9VHVmliDMoOX-hnU2Gc0L5AGqQ",
    authDomain: "slugalert-b088a.firebaseapp.com",
    databaseURL: "https://slugalert-b088a-default-rtdb.firebaseio.com",
    projectId: "slugalert-b088a",
    storageBucket: "slugalert-b088a.appspot.com",
    messagingSenderId: "1033469379764",
    appId: "1:1033469379764:web:4af7efaeb77db5b12d03e1",
    measurementId: "G-DBRHLS2EBF"
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const docRef = doc(db, "users");
const docSnap = await getDoc(docRef);

if (docSnap.exists()) {
  console.log("Document data:", docSnap.data());
} else {
  // doc.data() will be undefined in this case
  console.log("No such document!");
}

export const writeToDB = async (data) => {
    console.log('addDoc');
    const docRef = await addDoc(collection(db, "users"), data);
    return docRef
    // return db.collection(collectionName).doc(document).set(data)
}

// export const writeAutoGeneratedToDB = async (collectionName, data) => {
//         const docRef = doc(collection,(db, collectionName))
//         return await setDoc(docRef, data)
//     }

// writeToDB(data);